### ISSUE TITLE
Move flow router code to lib folder?

### ISSUE THREAD

**Issue by avemulkar** [andrewliebchen/meteor-react-boilerplate#1]
As the lib folder is normally loaded first on the front end it is probably good to have the routing logic present in the lib folder.

**Comment by andrewliebchen** [comment]
That's a good idea. The original idea was to keep as much related code together as possible (which is one of the foundational points React tries to make)...but I've noticed on a larger project I'm using this structure with, there is sometimes a flash of the wrong page when switching. I wasn't sure what was causing it, but maybe it was this.

FWIW, some [boilerplates](https://github.com/dfischer/meteor-boilerplate) place `routes.js` in `/lib` while plenty [others](https://github.com/matteodem/meteor-boilerplate) have a dedicated `/routes` folder. I think I like your idea the best.

**Comment by avemulkar** [comment]
Sounds good. Thanks for getting back to me!

**Comment by andrewliebchen** [comment]
I'm going to leave it as is for now. Maybe in some instances it will matter, but for prototyping and developer efficiency, its neat to have the routes with the component when possible.
